services:
  db:
    image: rest-api-dotnet-db
    container_name: database
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: rest-api-dotnet/Database/Dockerfile
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3308:3306"
    networks:
      - fabris-network
  rest-api-dotnet:
    image: rest-api-dotnet
    container_name: backend
    build:
      context: .
      dockerfile: rest-api-dotnet/Dockerfile
    environment:
      TZ: ${TZ}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "81:80"
    volumes:
      - ./nginx/ssl/nginx-selfsigned.crt:/nginx-selfsigned.crt
      - ./nginx/ssl/nginx-selfsigned.key:/nginx-selfsigned.key
    depends_on:
      - db
    networks:
      - fabris-network
  nginx:
    image: nginx:1.21
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ./rest-api-dotnet/nginx:/etc/nginx
      - ./rest-api-dotnet/nginx/cert:/cert
networks:
  fabris-network:
    driver: bridge
